project:
  type: website
  output-dir: _site/zh

website:
  title: "Benjamin Peeters"
  site-url: "https://benjaminpeeters.github.io/zh"

  navbar:
    background: primary
    search: true
    left:
      - text: "主页"
        href: zh/index.qmd
      - text: "出版物"
        href: zh/publications.qmd
      - text: "博客"
        href: zh/blog/index.qmd
      - text: "数据与代码"
        href: zh/data-code.qmd
      - text: "教学"
        href: zh/teaching.qmd
    right:
      - text: "EN"
        href: ../index.html
      - text: "FR"
        href: ../fr/index.html
      - icon: github
        href: https://github.com/benjaminpeeters
        aria-label: GitHub

  page-footer:
    left: |
      Benjamin Peeters - PIK博士后研究员
    center: |
      [ORCID: 0000-0002-5095-2021](https://orcid.org/0000-0002-5095-2021)
    right: |
      使用[Quarto](https://quarto.org/)构建

format:
  html:
    theme:
      light: [cosmo, custom.scss]
      dark: [darkly, custom-dark.scss]
    css: ../styles.css
    toc: true
    lang: zh

bibliography: ../publications.bib
